# Generated by Django 3.1 on 2020-08-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='end_field',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='drive',
            name='end_time',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='drive',
            name='end_transition',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='drive',
            name='pos_time',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='drive',
            name='start_field',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='drive',
            name='start_time',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='drive',
            name='start_transition',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='game',
            name='phase',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='game',
            name='stadium',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='play',
            name='description',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='play',
            name='end_yardline',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='play',
            name='play_type',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='play',
            name='start_yardline',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='play',
            name='time',
            field=models.TextField(default='N/A'),
        ),
    ]
