# Generated by Django 3.1 on 2020-08-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200825_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='end_field',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='end_time',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='end_transition',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='first_downs',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='penalty_yards',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='play_count',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='pos_time',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='start_field',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='start_time',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='start_transition',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='yards_gained',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_score',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_score_ot',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_score_q1',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_score_q2',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_score_q3',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_score_q4',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_score',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_score_ot',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_score_q1',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_score_q2',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_score_q3',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_score_q4',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='phase',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='stadium',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='weather',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='end_yardline',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='first_down',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='penalty',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='play_type',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='start_yardline',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='time',
            field=models.TextField(null=True),
        ),
    ]
