# Generated by Django 3.1 on 2020-08-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20200825_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='attendance',
            field=models.IntegerField(null=True),
        ),
    ]
