# Generated by Django 3.1 on 2020-08-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20200826_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
